# Generated by Django 5.0 on 2023-12-28 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_comment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created_at",
        ),
    ]
